version: '3.9'

networks:
  laravel:
    driver: bridge

services:
  laravel_workflow_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_workflow_app
    env_file: .env
    ports:
      - ${PORT:-80}:80
    networks:
      - laravel
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
