version: '3.9'

networks:
  laravel:

services:
  lumen_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      - PORT=80
      - DB_DATABASE=/app/database/database.sqlite
      - DB_CONNECTION=sqlite
      - DB_USERNAME=email-lumen
      - DB_PASSWORD=secret
    ports:
      - 80:80
      - 443:443
    networks:
      - laravel
