version: '3.9'

networks:
  laravel:

services:
  workflow_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_workflow_app
    environment:
      - PORT=80
    ports:
      - 80:80
      - 443:443
    networks:
      - laravel
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    depends_on:
      - mysql
    restart: always
  workflow-mysql:
    image: mysql:8.0
    restart: always
    container_name: workflow-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=#W0rkfl0w!!
      - MYSQL_DATABASE=workflow-orchestration
      - MYSQL_USER=workflow
      - MYSQL_PASSWORD=#W0rkfl0w!!
    networks:
      - laravel
    ports:
      - 8001:3306
volumes:
    mysql-data:
